### ISSUE TITLE
The macro `@includetests` has been silently dropped

### ISSUE THREAD

**Issue by Teo-ShaoWei** [ssfrr/TestSetExtensions.jl#25]
Putting a stake so the issue is searchable in GitHub, in case anyone is in the same shoes as me: Using `TestSetExtensions.jl` in a production app, and suddenly realizing that `@includetests` is gone in v3.0.0, but we can't retrieve v2.0.0 from Julia registry anymore, wanting to come here and quickly figure out why.

Hope to hear from the author and active maintainers instead of me guessing what happened. Feel free to write into the README if possible too. That might help many others who rely on your package to mitigate accordingly.

## disclaimer first

I respect that open-source work is on volunteering basis without pay. Even though my org is non-profit, there shouldn't be any expectation from me that my needs are satisfied continuously via free efforts (so I've made a PR myself if I need things done too haha). Also, the fact that I am using it in production reflects that this package has been carefully crafted by the authors and contributors, for that I appreciate alot.

On the other hand, there are some expectations for a mature ecosystem, and not adhering to those will reflect badly on Julia being suitable for production use. Most of these expectations are about what not to do that will not do justice to the effort that went in. So I think they are as applicable in a company/org as much as in open-source.

I'll share what I think didn't go right, but it ain't to pin responsibility, but rather to constructively see that there's a way to do better and let's all do so together next time.

## pain points
Ok so here we go:

### tag to v2.0.0 is gone

Since Julia registry works by relying on the repos themselves to point to the commit to check out, and only perform a `git-tree-sha1` to check that all files in the directory are as expected, there's no way to draw it out. It doesn't just affect `Pkg.add`. Methods like `Pkg.instantiate` which should ensure that the exact state of a `Manifest.toml` is checked out, can no longer do so.

Reproducibility is essential for production apps. If a version has seen the world, then there's an expectation to keep it immutable. There are some ways to manage issues, e.g. if v2.0.0 is unsavable, then release a v2.0.1 with the README saying not to use it at all and how to workaround.

### `@includetests` is gone without any deprecation

Next, in #23 by @palday, `@includetests` has been removed. The reason is to streamline the codebase, which is an intention that makes sense.

However, we can't just assume that no one around the world is relying on it in a non-trivial way. E.g. for my org we happened to be using `@includetests` inside another macro that collect all `*_test.jl` files within a directory recursively, like how pytest / Jest etc are doing. Pulling the rug like this suddenly is really painful. And I think currently Julia doesn't have a decent test framework somehow... weirdly... would be interested to be proven wrong.

So there are a few ways to manage deprecation without much effort. Some examples:
1. Make the changes needed as one version, e.g. @palday's useful test + CI changes could have been a PR by itself, separated from the removal of `@includetests`.
2. Version before/after the deprecation. These are the rationale to trigger a major version up, and it's good to isolate them. Then commit before could be v2.1.0, the after being v3.0.0. Users at least have a quick way of isolating the breaking commits instead of needing a git blame or equivalent.
3. Write deprecation reason within README. Or write the issue with the keyword. Idea is to make the term searchable in GitHub, helping people to quickly figure out what happened. Calling `@includetests` the "drops the special include stuff" violates that.

**Comment by ssfrr** [comment]
Sorry you got bit by this. It definitely would have been gentler to have a cycle of deprecation.

I'm surprised you can't install 2.0.0 though. Given that the General registry [has the commit hash](https://github.com/JuliaRegistries/General/blob/master/T/TestSetExtensions/Versions.toml) I would assume that it would use that to check out the right commit.

I'll try adding a `v2.0.0` tag and release pointing that the right commit, and hopefully that should make it installable again.

**Comment by palday** [comment]
Version 2.0.0 is retrievable from the Julia Registry:

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.4 (2023-11-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

[ Info: using Revise.jl
[ Info: using OhMyREPL.jl
(@v1.9) pkg> activate --temp
  Activating new project at `/var/folders/yy/nyj87tsn7093bb7d84rl64rh0000gp/T/jl_E4fbsj`

(jl_E4fbsj) pkg> add TestSetExtensions@2
   Resolving package versions...
   Installed TestSetExtensions ─ v2.0.0
    Updating `/private/var/folders/yy/nyj87tsn7093bb7d84rl64rh0000gp/T/jl_E4fbsj/Project.toml`
⌃ [98d24dd4] + TestSetExtensions v2.0.0
    Updating `/private/var/folders/yy/nyj87tsn7093bb7d84rl64rh0000gp/T/jl_E4fbsj/Manifest.toml`
  [ab62b9b5] + DeepDiffs v1.2.0
⌃ [98d24dd4] + TestSetExtensions v2.0.0
  [2a0f44e3] + Base64
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
        Info Packages marked with ⌃ have new versions available and may be upgradable.
Precompiling project...
  1 dependency successfully precompiled in 1 seconds. 1 already precompiled.
```

**Comment by ssfrr** [comment]
I was wrong about those being the commit hashes, I think they're just used to verify that the right thing was downloaded (which now I understand what @Teo-ShaoWei was talking about in the original post).

That said, I also verified that I can install v2 on a clean julia installation. I'm not actually sure how Julia is finding it though, as there's no "v2.0.0" tag and it doesn't seem that the General registry has the corresponding commit hash...

**Comment by ssfrr** [comment]
Also, for some context, I hadn't been actively maintaining this package for a few years, so was very happy and grateful when @palday wanted to spruce it up. I'm actually pleasantly surprised that it continued to work for so long without active maintenance.

In an ideal world we'd always go through a deprecation cycle for breaking changes, and maintain a changelog so folks could stay up to speed. That said, I'm grateful to accept contributions and think the improvements are worth it, even if we just rely on SemVer to account for breaking changes. As you said, it's a volunteer effort so I'd rather keep the project moving.

I will try to be more careful in the future though. I hadn't thought about this package in a long time and had basically abandoned it, but never communicated that. I wrongly assumed that it wasn't really in active use, and that's on me.

Now, if you had a 2.x upper bound in your Project.toml and something broke and v2.0.0 became uninstallable, that shouldn't happen and would be a bigger problem. Can you double check and make sure you're not able to install it?

**Comment by palday** [comment]
I have now added a `v2.0.0` tag to this repository.

Why does the tree-hash suffice? The git-tree-hash refers to the internal blob that git uses to represent to store the repository state. Commits point to various blob objects, so if you're willing to dig into the "plumbing" layer (instead of the "porcelain" layer), you can use the tree-hash to get back to a particular state.

**Comment by palday** [comment]
I'm sorry for the disruption here, but like @ssfrr I also assumed that there weren't many active users. I was completely reliant on the SemVer number to communicate the breakage because I also assumed that compatibility entries would keep people from accidentally upgrading, but the registry doesn't enforce compatibility entries for test dependencies. 🙁 

Sorry for the trouble, but the fix is hopefully easy: add an appropriate compat entry and things should hopefully just work.

**Comment by Teo-ShaoWei** [comment]
Hey @ssfrr / @palday thanks a lot for the quick response. My bad for the guilt-tripping. I can see the effort that goes into your work and we all occasionally have our oversights. I am thankful you take my comment/suggestion in good stride ❤️

We did an AAR on our side and thought I should keep us in the loop too.

What happened seems to be that `Pkg.test` actually doesn't take into account of `test/Manifest.toml`! >_< So even though we listed `TestSetExtensions@2.0.0` in that manifest, `TestSetExtensions@3.0.0` got released and `Pkg.test` use that instead. This broke our CI due to the `@includetests` deletion. Since our app is on EOL already, there isn't active devs on it, so some of us were forced to scramble. In my first-hour analysis, I came to this repo, and found that it doesn't have a v2.0.0 tag. My knee-jerk thought would be that I've found the cause, but I'm wrong. I apologize for the error in that deduction 🙇

For now, we mitigated by moving out all our test dependencies to the main `Project.toml` and `Manifest.toml` instead, which are respected by `Pkg.test`. While it isn't exactly a good practice to have test packages within production code, it makes sense for a life-support app.

Let's close this issue. Thank you for the good work 💪 Cheers! 🥂

**Comment by ssfrr** [comment]
No problem, I know it's stressful when things break unexpectedly, and I took your message as constructive suggestions.

I have a vague memory that `test/Manifest.toml` can be problematic and it's a better idea to keep everything in the main `Manifest.toml`, which it sounds like you discovered the hard way. It's a bummer because aside from this gotcha, it does seem cleaner to have a separate `test/Manifest.toml`. There's some more discussion about this issue [here](https://github.com/JuliaLang/Pkg.jl/issues/1788)

I'm not sure if this is what you're already doing, but you can still keep your test dependencies separated out so they don't get installed as regular dependencies of your package. For example you can see this [Project.toml](https://github.com/ssfrr/TestSetExtensions.jl/blob/8c26affc3ad588a9d673bbf9460afec975b9ff0e/Project.toml#L21-L28)
